### ISSUE TITLE
Other term instead of "constrained"?

### ISSUE THREAD

**Issue by mwelzl** [mwelzl/draft-ccwg-constrained-increase#1]
From Tom's email:

I am not sure about introducing a new term 'constrained' when there exists a historic term 'application-limited'.  Is there a reason you are avoiding 'application-limited'?  'bounded' may also be a more commonly used term in this regard.

**Comment by gorryfair** [comment]
My PR #3  tried to remove some of this - its would be possible to remove all use of constrained if we wish.

**Comment by mwelzl** [comment]
I'll do that, I'll change everything to directly say "rate limited".
